### ISSUE TITLE
Opening the search messes with placement of other HUD elements

### ISSUE THREAD

**Issue by megahead11** [jeremiahverba/qss#10]
Hi! I maintain the repo for Theatre inserts.
I don't know why exactly, but activating and using your module causes the HUD to get displaced or stretched in odd ways for Theatre Inserts.
This also seems to happen to GM screen and Calendar/Weather as well. 

Here's what it looks like...

Before:
![image](https://user-images.githubusercontent.com/21242682/114848040-2c110b80-9d93-11eb-8402-ad05c4d64d46.png)

After opening status search:
![image](https://user-images.githubusercontent.com/21242682/114848233-582c8c80-9d93-11eb-86c3-1d31782499f6.png)

**Comment by megahead11** [comment]
I wanted to do a pull request but I'm not sure how to do it since you have your module setup a bit different than I'm accustomed to, however
 the solution to this for non-pf systems is to edit line 35 of scripts/qss.js
You want ``buttonsToFilter = $(`.control-icon [title*='${searchTermTransformed}']`);`` instead because what you had before appears to catch all the css code and toggles it, causing the interface to mess up as shown above.
This worked for me, at least.

**Comment by JLtheking2** [comment]
Can vouch that this issue is happening and was really irritating, but megahead11's fix works! 😄

**Comment by jeremiahverba** [comment]
Should be addressed in 1.6.2
