### ISSUE TITLE
When updating module getting "k is not defined".

### ISSUE THREAD

**Issue by SabreRunner** [jeremiahverba/qss#13]
![image](https://user-images.githubusercontent.com/10673434/122289173-133fe600-cefb-11eb-80e3-9a4764922e66.png)

**Comment by jeremiahverba** [comment]
What version are you currently on?

**Comment by SabreRunner** [comment]
I'm on 1.0.0. I guess it hasn't updated since.

**Comment by jeremiahverba** [comment]
Use this link to install: 
https://raw.githubusercontent.com/jeremiahverba/qss/main/src/module.json
from the manual install button in foundry's module management area.
