### ISSUE TITLE
Filtering PF2 statuses doesn't work

### ISSUE THREAD

**Issue by rlach** [jeremiahverba/qss#16]
Foundry 8.7.0
QSS 1.7.0
PF2 2.4.0

No other modules

Filter bar appears above the statuses. Entering any character into search bar just does nothing, all statuses are always visible.

<img width="451" alt="Zrzut ekranu 2021-06-22 o 17 24 12" src="https://user-images.githubusercontent.com/5655000/122953003-ab682000-d37e-11eb-9f76-27a64892b672.png">

**Comment by jeremiahverba** [comment]
I am aware.  Fix is in progress. I apologize for the error.

**Comment by jeremiahverba** [comment]
This should be resolved with 1.8.0
