### ISSUE TITLE
Has stopped functioning

### ISSUE THREAD

**Issue by Bryn1701** [jeremiahverba/qss#17]
As the title states, this module has stopped functioning in Foundry 0.8.7 and D&D5e system 1.3.6 No error messages are produced, it just simply doesn't filter. It was working fine in 0.8.6

**Comment by jeremiahverba** [comment]
I believe v1.8.0 should resolve your issue.

**Comment by Bryn1701** [comment]
I can't seem to update to 1.8.0. The manifest points to version 1.7.0
