### ISSUE TITLE
X does not remove the text in the filter

### ISSUE THREAD

**Issue by GambetTV** [jeremiahverba/qss#18]
You have a handy X to click on that I imagine is meant to clear the text from the search bar. Right now it doesn't do anything. Also you can't seem to use the mouse to select your text for quick deletion. Ctrl A to select all does work, and backspace does work. Just needs some touching up.

I should point out that Vanilla, this module doesn't work at all. Doesn't filter anything. Thankfully I'm using this in conjunction with Monk's Little Details and it works fine in that. The X doesn't work either way though.

**Comment by jeremiahverba** [comment]
Thanks for the info.  I should probably update the module to list only dnd5e and pf2e as supported systems / requirements.  I admit I haven't tested it in a vanilla world.  

In v.1.8.0 of the module I removed the x.  It's a feature of the HTML5 input type "search" and foundry's status selector is set to hide on any click that is outside of it's bounds.  For this reason, I had to make the input control for the quick status select kill those click events so clicking in the input doesn't hide the entire status select menu.  That x is part of that click event, so it's just gone.  I have no trouble using ctrl+a or backspace or mouse selecting the text.  Can you confirm those issues still persist in 1.8.0 in dnd5e or pf2e systems?

**Comment by GambetTV** [comment]
The problem seems to be fixed, however, there's now a catastrophic bug occurring. If you open up a token's "Assign Status Effect" box and the box would open up off screen, the whole "screen" gets shifted over to make room for it, creating a huge deadspace in Foundry that can only be fixed by refreshing. 

![image](https://user-images.githubusercontent.com/72000497/125207159-acdb8880-e258-11eb-9041-78cb960b6fe7.png)

**Comment by jeremiahverba** [comment]
This is working as intended.  It's an unfortunate side effect of how Foundry handles "focus" as far as I can tell.
