### ISSUE TITLE
Incompatible with Status Icon Counters

### ISSUE THREAD

**Issue by megahead11** [jeremiahverba/qss#2]
Doesn't appear to work with Status Icon Counters. https://foundryvtt.com/packages/statuscounter/
When you use said module, it appears this one completely overrides the click-rebind behaviour of increasing/decreasing stacks. Adding status icons and once again clicking them with left click completely removes the status. Haven't tested if it does the same with number rebind.

**Comment by jeremiahverba** [comment]
I will look into adding support for this.

**Comment by jeremiahverba** [comment]
In the latest version, this should no longer be an issue.
