### ISSUE TITLE
Players can not access status effects

### ISSUE THREAD

**Issue by Avitale34** [jeremiahverba/qss#3]
Hello I have not been able to get this to work for players but it works great for GMs.

**Comment by jeremiahverba** [comment]
It should work for anyone on any token that they are the owner of.  I could possibly expand the permission-scope to allow different permissions.  How do you normally handle the permissions in your game?  With that insight, maybe I could cook up something that will work.

**Comment by jeremiahverba** [comment]
This should be resolved now. (v.1.4.0)  I made the entire module MUCH simpler.
