### ISSUE TITLE
[BUG] Status names not localized

### ISSUE THREAD

**Issue by arbron** [jeremiahverba/qss#4]
The module appears to be using the localization key in the list rather than actually localizing the names. This is obviously a problem if you are using a language other than English, but it also causes problems in English with words running together (e.g. "MagicShield" instead of "Magic Shield") and with other modules that introduce custom effects (see below):

<img width="277" alt="Screen Shot 2021-03-09 at 10 28 40" src="https://user-images.githubusercontent.com/19979839/110519620-661b2d80-80c2-11eb-9818-aaaa200d1b75.png">

**Comment by jeremiahverba** [comment]
I'll look into this.  Thanks for the heads up.

**Comment by jeremiahverba** [comment]
This should be fixed in 1.3.0 !

If you have trouble updating, uninstall /reinstall or use this manifest url to install:
https://raw.githubusercontent.com/jeremiahverba/qss/main/src/module.json
