### ISSUE TITLE
Bug when updating from module.json

### ISSUE THREAD

**Issue by apoapostolov** [jeremiahverba/qss#5]
![image](https://user-images.githubusercontent.com/4083812/111025054-90365d80-83ea-11eb-8d82-616c2b9bae5d.png)

**Comment by jeremiahverba** [comment]
this should be addressed moving forward, if you still have the issue, uninstall the mod, and install 1.3.0 from the module finder or use this url:
https://raw.githubusercontent.com/jeremiahverba/qss/main/src/module.json
