### ISSUE TITLE
Support for Monk's Little Details mod

### ISSUE THREAD

**Issue by apoapostolov** [jeremiahverba/qss#7]
The mod adds a plethora of useful custom conditions to 5E. Their names can be derived easily from their technical names with which they are registered, so support is just cleaning the technical prefixes and putting space between camelcase words.

For example MonksLittleDetails.StatusCharmed needs to become Charmed

![image](https://user-images.githubusercontent.com/4083812/111025249-8fea9200-83eb-11eb-8420-16f1077c9027.png)

**Comment by jeremiahverba** [comment]
This might be related to #4 .  I'll look into it.

**Comment by jeremiahverba** [comment]
This should be fixed in 1.3.0 !

If you have trouble updating, uninstall /reinstall or use this manifest url to install: 
https://raw.githubusercontent.com/jeremiahverba/qss/main/src/module.json
