### ISSUE TITLE
Add ability to right-click condition to use large icon (as per normal picker)

### ISSUE THREAD

**Issue by brother-oak** [jeremiahverba/qss#8]
Am liking the mod - thanks.
When you use the normal condition picker, you can left click each of the icons to add it to the token and it appears as a small icon next to the token. However, you can also right-click on a single condition icon and it will be displayed as a large version overlaid on the token itself. This is really useful for indicating DEAD, for example, or to emphasize a particular condition.

This functionality is not present in this mod - it only adds the small icons. Can it be modified to allow right-clicking too, to mimic the default picker functionality?

**Comment by jeremiahverba** [comment]
This should be resolved now. (v.1.4.0)  I made the entire module MUCH simpler.  

The extra list of conditions is gone, in favor of simply filtering the condition buttons that already exist.  This way the left / right click behavior of those buttons is still useable.
