### ISSUE TITLE
[Bug] Loading template files outside application or user data locations

### ISSUE THREAD

**Issue by arbron** [jeremiahverba/qss#9]
The module works fine, but on startup I get the following error in the console:

```
Uncaught (in promise) Error: You are not allowed to load template files outside of the application or user data locations
    at n.<anonymous> (foundry.js:5952)
```

The path it is trying to load when the error occurs is "./../templates/qss.hbs". This appears to be happening in "module/preloadTemplates.ts".

**Comment by jeremiahverba** [comment]
This should be resolved now. (v.1.4.0)  I made the entire module MUCH simpler.
